# Generated by Django 4.0.5 on 2022-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='USD', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='premium_plan',
            field=models.CharField(default='Free', max_length=255),
        ),
    ]
