# Generated by Django 4.0.5 on 2022-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premium_remove_userprofile_api_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.IntegerField(default=0),
        ),
    ]
