# Generated by Django 4.0.5 on 2022-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_api_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
