# Generated by Django 4.0.5 on 2022-08-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
