# Generated by Django 4.0.5 on 2022-08-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
