# Generated by Django 4.0.5 on 2022-08-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_currency_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
