# Generated by Django 4.0.5 on 2022-08-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_users_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_prod',
            name='order_id',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
