# Generated by Django 4.0.5 on 2022-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_users_prod_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Catalog'},
        ),
        migrations.AddField(
            model_name='users_prod',
            name='product_name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
