# Generated by Django 4.0.5 on 2022-08-02 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_catalog_options_users_prod_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_prod',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
