# Generated by Django 4.0.5 on 2022-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['-date']},
        ),
    ]
