# Generated by Django 4.0.5 on 2022-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
