# Generated by Django 4.0.5 on 2022-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_desc',
            field=models.CharField(default='none', max_length=10000),
        ),
    ]
