# Generated by Django 4.0.5 on 2022-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_company_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='lastDiv',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='stock',
            name='website',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
