# Generated by Django 4.0.5 on 2022-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock_avg_price_stock_cur_value_stock_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
